"""add important points

Revision ID: 2bf54b5d5ccc
Revises: 36eabee0d071
Create Date: 2026-08-09 16:45:48.934914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf54b5d5ccc'
down_revision: Union[str, Sequence[str], None] = '36eabee0d071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_important_points_id'), 'important_points', ['id'], unique=False)
    op.create_index(op.f('ix_important_points_material_id'), 'important_points', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_important_points_material_id'), table_name='important_points')
    op.drop_index(op.f('ix_important_points_id'), table_name='important_points')
    op.drop_table('important_points')
    # ### end Alembic commands ###
