"""add generated summaries

Revision ID: 36eabee0d071
Revises: e30aaf0dfea4
Create Date: 2026-08-09 16:43:17.747218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36eabee0d071'
down_revision: Union[str, Sequence[str], None] = 'e30aaf0dfea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_summaries_id'), 'generated_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_generated_summaries_material_id'), 'generated_summaries', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_summaries_material_id'), table_name='generated_summaries')
    op.drop_index(op.f('ix_generated_summaries_id'), table_name='generated_summaries')
    op.drop_table('generated_summaries')
    # ### end Alembic commands ###
