"""Add mock test tables

Revision ID: 9d9605525265
Revises: c8dc12a2be91
Create Date: 2026-08-10 00:48:40.162261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9605525265'
down_revision: Union[str, Sequence[str], None] = 'c8dc12a2be91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_id'), 'mock_tests', ['id'], unique=False)
    op.create_index(op.f('ix_mock_tests_material_id'), 'mock_tests', ['material_id'], unique=False)
    op.create_index(op.f('ix_mock_tests_user_id'), 'mock_tests', ['user_id'], unique=False)
    op.create_table('mock_test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_questions_id'), 'mock_test_questions', ['id'], unique=False)
    op.create_index(op.f('ix_mock_test_questions_mock_test_id'), 'mock_test_questions', ['mock_test_id'], unique=False)
    op.create_index(op.f('ix_mock_test_questions_question_id'), 'mock_test_questions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_test_questions_question_id'), table_name='mock_test_questions')
    op.drop_index(op.f('ix_mock_test_questions_mock_test_id'), table_name='mock_test_questions')
    op.drop_index(op.f('ix_mock_test_questions_id'), table_name='mock_test_questions')
    op.drop_table('mock_test_questions')
    op.drop_index(op.f('ix_mock_tests_user_id'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_material_id'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_id'), table_name='mock_tests')
    op.drop_table('mock_tests')
    # ### end Alembic commands ###
