"""Add mock test attempts and answers

Revision ID: 9d98d0ec3e2f
Revises: 9d9605525265
Create Date: 2026-08-10 13:51:34.984631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d98d0ec3e2f'
down_revision: Union[str, Sequence[str], None] = '9d9605525265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_attempts_id'), 'mock_test_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_mock_test_attempts_mock_test_id'), 'mock_test_attempts', ['mock_test_id'], unique=False)
    op.create_index(op.f('ix_mock_test_attempts_user_id'), 'mock_test_attempts', ['user_id'], unique=False)
    op.create_table('mock_test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['mock_test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_answers_attempt_id'), 'mock_test_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_mock_test_answers_id'), 'mock_test_answers', ['id'], unique=False)
    op.create_index(op.f('ix_mock_test_answers_question_id'), 'mock_test_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_test_answers_question_id'), table_name='mock_test_answers')
    op.drop_index(op.f('ix_mock_test_answers_id'), table_name='mock_test_answers')
    op.drop_index(op.f('ix_mock_test_answers_attempt_id'), table_name='mock_test_answers')
    op.drop_table('mock_test_answers')
    op.drop_index(op.f('ix_mock_test_attempts_user_id'), table_name='mock_test_attempts')
    op.drop_index(op.f('ix_mock_test_attempts_mock_test_id'), table_name='mock_test_attempts')
    op.drop_index(op.f('ix_mock_test_attempts_id'), table_name='mock_test_attempts')
    op.drop_table('mock_test_attempts')
    # ### end Alembic commands ###
