"""add subject to mock tests

Revision ID: f482f59fb66e
Revises: c6c9a1133cda
Create Date: 2026-08-17 22:53:14.194556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f482f59fb66e'
down_revision: Union[str, Sequence[str], None] = 'c6c9a1133cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_tests', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.alter_column('mock_tests', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_mock_tests_subject_id'), 'mock_tests', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'mock_tests', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mock_tests', type_='foreignkey')
    op.drop_index(op.f('ix_mock_tests_subject_id'), table_name='mock_tests')
    op.alter_column('mock_tests', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('mock_tests', 'subject_id')
    # ### end Alembic commands ###
